import {useEffect,useRef,useState} from "react";
import Loading from "./components/Loading.jsx";
import CacheTable from "./components/CacheTable.jsx";
import CacheForm from "./components/CacheForm.jsx";
import {listEntries,createEntry,updateEntry,deleteEntry} from "./services/redisApi.js";
import {sanitizeText} from "./utils/sanitize.js";
const analytics=(a,d={})=>console.log(`[Analytics] User interacted with Redis Caching: ${a}`,d);
export default function App(){const [entries,setEntries]=useState([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modal,setModal]=useState(null),[saving,setSaving]=useState(false);const timer=useRef();
async function load(term=search){setLoading(true);setError("");try{setEntries(await listEntries(term))}catch(e){setError(e.message||"Redis service unavailable. Check your connection.")}finally{setLoading(false)}}
useEffect(()=>{load();return()=>clearTimeout(timer.current)},[]);
function searchChange(v){const clean=sanitizeText(v);setSearch(clean);clearTimeout(timer.current);timer.current=setTimeout(()=>{analytics("search cache entries",{term:clean});load(clean)},300)}
async function save(data){setSaving(true);try{if(modal?.id){await updateEntry(modal.id,data);analytics("update cache entry",{cacheKey:data.cacheKey})}else{await createEntry(data);analytics("create cache entry",{cacheKey:data.cacheKey})}setModal(null);await load()}catch(e){setError(e.message||"Could not save entry.")}finally{setSaving(false)}}
async function remove(e){if(!confirm(`Delete cache entry "${e.cacheKey}"?`))return;setLoading(true);try{await deleteEntry(e.id);analytics("delete cache entry",{cacheKey:e.cacheKey});await load()}catch(x){setError(x.message||"Could not delete entry.");setLoading(false)}}
return <main className="app-shell"><header className="app-header"><div><h1>Property Listings Cache</h1><p>Manage active Redis cache entries for floor staff.</p></div><button className="btn" onClick={()=>setModal({})} aria-label="Add a new cache entry">Add cache entry</button></header><div className="toolbar"><div className="field"><label htmlFor="search-input">Search by cache key</label><input id="search-input" type="search" value={search} onChange={e=>searchChange(e.target.value)} placeholder="e.g. listing:property:4471"/></div></div>{error&&<div className="status-line error-banner" role="alert">{error}</div>}{loading?<Loading/>:entries.length?<CacheTable entries={entries} onEdit={setModal} onDelete={remove}/>:<div className="status-line" role="status">{search?"No data found for that search.":"No data found. Add a cache entry to get started."}</div>}{modal&&<div className="modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">{modal.id?"Edit cache entry":"Add cache entry"}</h2><CacheForm entry={modal.id?modal:null} onSave={save} onCancel={()=>setModal(null)} saving={saving}/></section></div>}</main>}